# fsactl - install and manage your MSFS2020 addons
# Copyright (c) 2020  Michael Sasser <Michael@MichaelSasser.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.1.4

      - name: Install Project Dependencies
        run: poetry install -E docs

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Sphinx Build
        working-directory: ./docs
        run: make html

      - name: Test with pytest
        run: poetry run pytest